require 'lib/models/concerns/file_saveable'
require "lib/models/campaign"
require "lib/models/character"
require "lib/agents/campaign_agent"
require "debug"

# Better name ideas: Session, Run
# Tentative goal for this class:
#   - Serve as the interface for accessing the campaign's state and history
# Does that make sense? Or should the Agent be the central class and this just the agent's persistant log?
# TODOS:
#   - Store the persistent campaign state, like party and HP for the character and NPCs
#
class CampaignChat
  include FileSaveable
  storage_key "campaign_chats"

  attr_reader :id, :campaign_id, :player_character_id
  def initialize(id: SecureRandom.uuid, campaign_id: nil, campaign: nil, player_character_id: nil, player_character: nil, messages: [])
    @id = id
    @campaign = campaign
    @campaign_id = campaign_id || @campaign&.id
    @player_character = player_character
    @player_character_id = player_character_id || @player_character&.id
    @messages = messages
  end

  def add_message(type:, message:)
    messages << {
      type: type,
      message_content: message.content,
      timestamp: Time.now,
    }
  end

  def last_message_at
    messages.last&.fetch(:timestamp, nil)
  end

  def campaign
    @campaign ||= Campaign.find(@campaign_id)
  end

  def player_character
    return nil unless @player_character_id
    @player_character ||= Character.find(@player_character_id)
  end

  def start!
    campaign_agent.start!
    update_messages!
  end

  def started?
    messages.any?
  end

  def messages
    @messages || []
  end

  def displayable_messages
    # the first user message is the message to start the campaign, generated by the system
    messages.select { |msg| msg["role"].to_s == "assistant" || msg["role"].to_s == "user" }[1..]
  end

  def chat!(user_message:)
    campaign_agent.chat_stream(user_message: user_message)
    update_messages!
  end

  def last_exchange
    latest_user_message = displayable_messages.reverse.find { |msg| msg["role"].to_s == "user" }
    last_user_message_index = displayable_messages.index(latest_user_message)
    displayable_messages[
      last_user_message_index..-1
    ]
  end

  def campaign_agent
    return @campaign_agent if @campaign_agent

    @campaign_agent = CampaignAgent.new(campaign, player_character, self)
    @campaign_agent.load_messages!(messages: messages)
    @campaign_agent
  end

  # save all of the chat messages
  def update_messages!
    # remove system message, as this is always added by the agent
    @messages = campaign_agent.message_hashes.reject { |msg| msg["role"].to_s == "system" }
    save
  end

  def to_hash
    {
      id: id,
      campaign_id: campaign_id,
      player_character_id: player_character_id,
      messages: messages.map(&:to_hash),
    }
  end

  def self.find_by(campaign_id: nil, player_character_id: nil)
    return nil if campaign_id.nil? && player_character_id.nil?

    all.find do |chat|
      matching_campaign = campaign_id ? chat.campaign_id == campaign_id : true
      matching_player_character = player_character_id ? chat.player_character_id == player_character_id : true
      matching_campaign && matching_player_character
    end
  end

  def self.for_campaign(campaign_id)
    all.select { |c| c.campaign_id == campaign_id }
  end
end
